/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songti16.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0000 - 007F                                  *
* Range enabled:        4E91 - 4E91                                  *
* Range enabled:        6D32 - 6D32                                  *
* Range enabled:        667A - 667A                                  *
* Range enabled:        80FD - 80FD                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0021[ 11] = { /* code 0021, EXCLAMATION MARK */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0022[  4] = { /* code 0022, QUOTATION MARK */
  __X__X__,
  _XX_XX__,
  _X__X___,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0023[ 11] = { /* code 0023, NUMBER SIGN */
  __X__X__,
  __X__X__,
  __X__X__,
  XXXXXXX_,
  _X__X___,
  _X__X___,
  _X__X___,
  XXXXXXX_,
  _X__X___,
  _X__X___,
  _X__X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0024[ 14] = { /* code 0024, DOLLAR SIGN */
  __X_____,
  _XXX____,
  X_X_X___,
  X_X_X___,
  X_X_____,
  _XX_____,
  __XX____,
  __X_X___,
  __X_X___,
  X_X_X___,
  X_X_X___,
  _XXX____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0025[ 11] = { /* code 0025, PERCENT SIGN */
  _X___X__,
  X_X__X__,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  _X_X_X__,
  ___XX_X_,
  __X_X_X_,
  __X_X_X_,
  __X_X_X_,
  _X___X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0026[ 11] = { /* code 0026, AMPERSAND */
  __XX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X_X____,
  _XX_XXX_,
  X_X__X__,
  X__X_X__,
  X___X___,
  X___X__X,
  _XXX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0027[  4] = { /* code 0027, APOSTROPHE */
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0028[ 14] = { /* code 0028, LEFT PARENTHESIS */
  ___X____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0029[ 14] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002A[  8] = { /* code 002A, ASTERISK */
  ___X____,
  ___X____,
  XX_X_XX_,
  __XXX___,
  __XXX___,
  XX_X_XX_,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002B[  9] = { /* code 002B, PLUS SIGN */
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002C[  4] = { /* code 002C, COMMA */
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_002F[ 13] = { /* code 002F, SOLIDUS */
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0030[ 11] = { /* code 0030, DIGIT ZERO */
  __XX____,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  _X__X___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0031[ 11] = { /* code 0031, DIGIT ONE */
  __X_____,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0032[ 11] = { /* code 0032, DIGIT TWO */
  _XXXX___,
  X____X__,
  X____X__,
  X____X__,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X____X__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0033[ 11] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  X____X__,
  X____X__,
  ____X___,
  __XX____,
  ____X___,
  _____X__,
  _____X__,
  X____X__,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0034[ 11] = { /* code 0034, DIGIT FOUR */
  ____X___,
  ___XX___,
  __X_X___,
  _X__X___,
  _X__X___,
  X___X___,
  X___X___,
  XXXXXX__,
  ____X___,
  ____X___,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0035[ 11] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  X_______,
  X_______,
  X_______,
  X_XX____,
  XX__X___,
  _____X__,
  _____X__,
  X____X__,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0036[ 11] = { /* code 0036, DIGIT SIX */
  __XXX___,
  _X__X___,
  X_______,
  X_______,
  X_XX____,
  XX__X___,
  X____X__,
  X____X__,
  X____X__,
  _X__X___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0037[ 11] = { /* code 0037, DIGIT SEVEN */
  XXXXXX__,
  X___X___,
  X___X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0038[ 11] = { /* code 0038, DIGIT EIGHT */
  _XXXX___,
  X____X__,
  X____X__,
  X____X__,
  _X__X___,
  __XX____,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0039[ 11] = { /* code 0039, DIGIT NINE */
  __XX____,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  _X__XX__,
  __XX_X__,
  _____X__,
  _____X__,
  _X__X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003A[  8] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003B[  9] = { /* code 003B, SEMICOLON */
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003C[ 11] = { /* code 003C, LESS-THAN SIGN */
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003D[  5] = { /* code 003D, EQUALS SIGN */
  XXXXXXX_,
  ________,
  ________,
  ________,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003E[ 11] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_003F[ 11] = { /* code 003F, QUESTION MARK */
  _XXXX___,
  X____X__,
  X____X__,
  XX___X__,
  _____X__,
  ____X___,
  ___X____,
  ___X____,
  ________,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0040[ 11] = { /* code 0040, COMMERCIAL AT */
  __XXX___,
  _X___X__,
  _X_XX_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_XX_X__,
  _X____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0041[ 11] = { /* code 0041, LATIN CAPITAL LETTER A */
  ___X____,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0042[ 11] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0043[ 11] = { /* code 0043, LATIN CAPITAL LETTER C */
  __XXXXX_,
  _X____X_,
  _X____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0044[ 11] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0045[ 11] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X____X_,
  _X____X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0046[ 11] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0047[ 11] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXX__,
  _X___X__,
  _X___X__,
  X_______,
  X_______,
  X_______,
  X___XXX_,
  X____X__,
  _X___X__,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0048[ 11] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0049[ 11] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004A[ 13] = { /* code 004A, LATIN CAPITAL LETTER J */
  __XXXXX_,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004B[ 11] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXX_XXX_,
  _X___X__,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  XXX_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004C[ 11] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004D[ 11] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  XX_X_XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004E[ 11] = { /* code 004E, LATIN CAPITAL LETTER N */
  XX___XXX,
  _XX___X_,
  _XX___X_,
  _X_X__X_,
  _X_X__X_,
  _X__X_X_,
  _X__X_X_,
  _X__X_X_,
  _X___XX_,
  _X___XX_,
  XXX___X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_004F[ 11] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0050[ 11] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0051[ 12] = { /* code 0051, LATIN CAPITAL LETTER Q */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_XX__X_,
  XX__X_X_,
  _X__XX__,
  __XXX___,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0052[ 11] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  _X____X_,
  XXX___XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0053[ 11] = { /* code 0053, LATIN CAPITAL LETTER S */
  _XXXXX__,
  X____X__,
  X____X__,
  X_______,
  _X______,
  __XX____,
  ____X___,
  _____X__,
  X____X__,
  X____X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0054[ 11] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXX_,
  X__X__X_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0055[ 11] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0056[ 11] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X___X__,
  __X__X__,
  __X__X__,
  __X_X___,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0057[ 11] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX_X_XX_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X_X_X_X_,
  X_X_X_X_,
  _XX_XX__,
  _X___X__,
  _X___X__,
  _X___X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0058[ 11] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  __X__X__,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0059[ 11] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005A[ 11] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXX_,
  X____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  _X____X_,
  _X____X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005B[ 14] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXX____,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005C[ 14] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ____X___,
  _____X__,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005D[ 14] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005E[  2] = { /* code 005E, CIRCUMFLEX ACCENT */
  _XXX____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0060[  2] = { /* code 0060, GRAVE ACCENT */
  XX______,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0061[  7] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXX___,
  X____X__,
  __XXXX__,
  _X___X__,
  X____X__,
  X____X__,
  _XXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0062[ 12] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0063[  7] = { /* code 0063, LATIN SMALL LETTER C */
  __XXX___,
  _X___X__,
  X_______,
  X_______,
  X_______,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0064[ 12] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ____XX__,
  _____X__,
  _____X__,
  _____X__,
  __XXXX__,
  _X___X__,
  X____X__,
  X____X__,
  X____X__,
  _X__XX__,
  __XX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0065[  7] = { /* code 0065, LATIN SMALL LETTER E */
  _XXXX___,
  X____X__,
  XXXXXX__,
  X_______,
  X_______,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0066[ 11] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXXX_,
  __X___X_,
  __X_____,
  __X_____,
  XXXXXX__,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0067[  9] = { /* code 0067, LATIN SMALL LETTER G */
  _XXXXX__,
  X___X___,
  X___X___,
  _XXX____,
  X_______,
  _XXXX___,
  X____X__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0068[ 12] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0069[ 11] = { /* code 0069, LATIN SMALL LETTER I */
  _XX_____,
  _XX_____,
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006A[ 13] = { /* code 006A, LATIN SMALL LETTER J */
  ___XX___,
  ___XX___,
  ________,
  ________,
  __XXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006B[ 12] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X__XXX_,
  _X__X___,
  _X_X____,
  _XX_X___,
  _X__X___,
  _X___X__,
  XXX_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006C[ 11] = { /* code 006C, LATIN SMALL LETTER L */
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006D[  7] = { /* code 006D, LATIN SMALL LETTER M */
  XXXXXXX_,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  XXX_XX_X};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006E[  7] = { /* code 006E, LATIN SMALL LETTER N */
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_006F[  7] = { /* code 006F, LATIN SMALL LETTER O */
  _XXXX___,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0070[  9] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0071[  9] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXX__,
  _X___X__,
  X____X__,
  X____X__,
  X____X__,
  _X___X__,
  __XXXX__,
  _____X__,
  ____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0072[  7] = { /* code 0072, LATIN SMALL LETTER R */
  XXX_XXX_,
  __XX__X_,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0073[  7] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  X____X__,
  X_______,
  _XXXX___,
  _____X__,
  X____X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0074[  9] = { /* code 0074, LATIN SMALL LETTER T */
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0075[  7] = { /* code 0075, LATIN SMALL LETTER U */
  XX___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0076[  7] = { /* code 0076, LATIN SMALL LETTER V */
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0077[  7] = { /* code 0077, LATIN SMALL LETTER W */
  XX_X_XXX,
  X__X__X_,
  X__X__X_,
  X_X_X_X_,
  X_X_X_X_,
  _X___X__,
  _X___X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0078[  7] = { /* code 0078, LATIN SMALL LETTER X */
  XX_XXX__,
  _X__X___,
  __XX____,
  __XX____,
  __XX____,
  _X__X___,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_0079[  9] = { /* code 0079, LATIN SMALL LETTER Y */
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007A[  7] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXX__,
  X___X___,
  ___X____,
  __X_____,
  __X_____,
  _X___X__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007B[ 14] = { /* code 007B, LEFT CURLY BRACKET */
  __XX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007C[ 16] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007D[ 14] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007E[  3] = { /* code 007E, TILDE */
  _XX____X,
  X__XX__X,
  X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_007F[  1] = { /* code 007F, <control> */
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_4E91[ 30] = { /* code 4E91 */
  __XXXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  ____X___,_X______,
  ___X____,__X_____,
  __X_____,___X____,
  _XXXXXXX,XXXXX___,
  __X_____,____X___,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_667A[ 32] = { /* code 667A */
  __X_____,________,
  __XXXXX_,_XXXXX__,
  _X__X___,_X___X__,
  ____X___,_X___X__,
  XXXXXXXX,_X___X__,
  ___X_X__,_X___X__,
  __X___X_,_XXXXX__,
  _X______,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_6D32[ 32] = { /* code 6D32 */
  _______X,_____X__,
  __X____X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,__X__X__,
  X______X,__X__X__,
  _X_____X,__X__X__,
  _X___X_X,X_XX_X__,
  ___X_X_X,_XX_XX__,
  ___XX__X,__X__X__,
  __X____X,__X__X__,
  XXX____X,__X__X__,
  __X____X,__X__X__,
  __X____X,__X__X__,
  __X___X_,__X__X__,
  __X___X_,_____X__,
  _____X__,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti16_80FD[ 32] = { /* code 80FD */
  ___X____,_X______,
  __X__X__,_X___X__,
  _X____X_,_X__X___,
  XXXXXXXX,_XXX____,
  _______X,_X______,
  ________,_X____X_,
  _XXXXXX_,_X____X_,
  _X____X_,__XXXXX_,
  _X____X_,________,
  _XXXXXX_,_X___X__,
  _X____X_,_X__X___,
  _X____X_,_XXX____,
  _XXXXXX_,_X______,
  _X____X_,_X____X_,
  _X__X_X_,_X____X_,
  _X___X__,__XXXXX_};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontsongti16_CharInfo[100] = {
   {   1,   1,   0,  14,   8, acGUI_Fontsongti16_0020 } /* code 0020, SPACE */
  ,{   2,  11,   3,   3,   8, acGUI_Fontsongti16_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   6,   4,   1,   1,   8, acGUI_Fontsongti16_0022 } /* code 0022, QUOTATION MARK */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0023 } /* code 0023, NUMBER SIGN */
  ,{   5,  14,   1,   2,   8, acGUI_Fontsongti16_0024 } /* code 0024, DOLLAR SIGN */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0025 } /* code 0025, PERCENT SIGN */
  ,{   8,  11,   0,   3,   8, acGUI_Fontsongti16_0026 } /* code 0026, AMPERSAND */
  ,{   3,   4,   0,   1,   8, acGUI_Fontsongti16_0027 } /* code 0027, APOSTROPHE */
  ,{   4,  14,   3,   1,   8, acGUI_Fontsongti16_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   4,  14,   1,   1,   8, acGUI_Fontsongti16_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   7,   8,   0,   4,   8, acGUI_Fontsongti16_002A } /* code 002A, ASTERISK */
  ,{   7,   9,   0,   4,   8, acGUI_Fontsongti16_002B } /* code 002B, PLUS SIGN */
  ,{   3,   4,   0,  12,   8, acGUI_Fontsongti16_002C } /* code 002C, COMMA */
  ,{   7,   1,   1,   8,   8, acGUI_Fontsongti16_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   1,  12,   8, acGUI_Fontsongti16_002E } /* code 002E, FULL STOP */
  ,{   7,  13,   1,   2,   8, acGUI_Fontsongti16_002F } /* code 002F, SOLIDUS */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  11,   1,   3,   8, acGUI_Fontsongti16_0031 } /* code 0031, DIGIT ONE */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0032 } /* code 0032, DIGIT TWO */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0033 } /* code 0033, DIGIT THREE */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0034 } /* code 0034, DIGIT FOUR */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0035 } /* code 0035, DIGIT FIVE */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0036 } /* code 0036, DIGIT SIX */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0037 } /* code 0037, DIGIT SEVEN */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0038 } /* code 0038, DIGIT EIGHT */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   8,   3,   6,   8, acGUI_Fontsongti16_003A } /* code 003A, COLON */
  ,{   2,   9,   2,   7,   8, acGUI_Fontsongti16_003B } /* code 003B, SEMICOLON */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_003C } /* code 003C, LESS-THAN SIGN */
  ,{   7,   5,   0,   6,   8, acGUI_Fontsongti16_003D } /* code 003D, EQUALS SIGN */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_003F } /* code 003F, QUESTION MARK */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0040 } /* code 0040, COMMERCIAL AT */
  ,{   8,  11,   0,   3,   8, acGUI_Fontsongti16_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   8,  11,   0,   3,   8, acGUI_Fontsongti16_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   5,  11,   1,   3,   8, acGUI_Fontsongti16_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   7,  13,   0,   3,   8, acGUI_Fontsongti16_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   8,  11,   0,   3,   8, acGUI_Fontsongti16_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   7,  12,   0,   3,   8, acGUI_Fontsongti16_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   8,  11,   0,   3,   8, acGUI_Fontsongti16_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   6,  11,   1,   3,   8, acGUI_Fontsongti16_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   8,  11,   0,   3,   8, acGUI_Fontsongti16_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   8,  11,   0,   3,   8, acGUI_Fontsongti16_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   8,  11,   0,   3,   8, acGUI_Fontsongti16_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   7,  11,   0,   3,   8, acGUI_Fontsongti16_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   4,  14,   3,   1,   8, acGUI_Fontsongti16_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   6,  14,   1,   2,   8, acGUI_Fontsongti16_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   4,  14,   1,   1,   8, acGUI_Fontsongti16_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   5,   2,   2,   1,   8, acGUI_Fontsongti16_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   8,   1,   0,  15,   8, acGUI_Fontsongti16_005F } /* code 005F, LOW LINE */
  ,{   3,   2,   1,   1,   8, acGUI_Fontsongti16_0060 } /* code 0060, GRAVE ACCENT */
  ,{   7,   7,   1,   7,   8, acGUI_Fontsongti16_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   7,  12,   0,   2,   8, acGUI_Fontsongti16_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   6,   7,   1,   7,   8, acGUI_Fontsongti16_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   7,  12,   1,   2,   8, acGUI_Fontsongti16_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   6,   7,   1,   7,   8, acGUI_Fontsongti16_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   7,  11,   1,   3,   8, acGUI_Fontsongti16_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   6,   9,   1,   7,   8, acGUI_Fontsongti16_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   8,  12,   0,   2,   8, acGUI_Fontsongti16_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   5,  11,   1,   3,   8, acGUI_Fontsongti16_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  13,   1,   3,   8, acGUI_Fontsongti16_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   7,  12,   0,   2,   8, acGUI_Fontsongti16_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   5,  11,   1,   3,   8, acGUI_Fontsongti16_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   8,   7,   0,   7,   8, acGUI_Fontsongti16_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   8,   7,   0,   7,   8, acGUI_Fontsongti16_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   6,   7,   1,   7,   8, acGUI_Fontsongti16_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   7,   9,   0,   7,   8, acGUI_Fontsongti16_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   7,   9,   1,   7,   8, acGUI_Fontsongti16_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   7,   7,   0,   7,   8, acGUI_Fontsongti16_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   7,   1,   7,   8, acGUI_Fontsongti16_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,   9,   1,   5,   8, acGUI_Fontsongti16_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,   7,   0,   7,   8, acGUI_Fontsongti16_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   8,   7,   0,   7,   8, acGUI_Fontsongti16_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   8,   7,   0,   7,   8, acGUI_Fontsongti16_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   6,   7,   1,   7,   8, acGUI_Fontsongti16_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   8,   9,   0,   7,   8, acGUI_Fontsongti16_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   6,   7,   1,   7,   8, acGUI_Fontsongti16_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   4,  14,   4,   1,   8, acGUI_Fontsongti16_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  16,   4,   0,   8, acGUI_Fontsongti16_007C } /* code 007C, VERTICAL LINE */
  ,{   4,  14,   1,   1,   8, acGUI_Fontsongti16_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   8,   3,   1,   0,   8, acGUI_Fontsongti16_007E } /* code 007E, TILDE */
  ,{   1,   1,   0,  14,   8, acGUI_Fontsongti16_007F } /* code 007F, <control> */
  ,{  15,  15,   0,   1,  16, acGUI_Fontsongti16_4E91 } /* code 4E91 */
  ,{  14,  16,   0,   0,  16, acGUI_Fontsongti16_667A } /* code 667A */
  ,{  14,  16,   0,   0,  16, acGUI_Fontsongti16_6D32 } /* code 6D32 */
  ,{  15,  16,   0,   0,  16, acGUI_Fontsongti16_80FD } /* code 80FD */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti16_Prop5 = {
   0x80FD /* first character */
  ,0x80FD /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 99] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti16_Prop4 = {
   0x6D32 /* first character */
  ,0x6D32 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 98] /* address of first character */
  ,&GUI_Fontsongti16_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti16_Prop3 = {
   0x667A /* first character */
  ,0x667A /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 97] /* address of first character */
  ,&GUI_Fontsongti16_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti16_Prop2 = {
   0x4E91 /* first character */
  ,0x4E91 /* last character  */
  ,&GUI_Fontsongti16_CharInfo[ 96] /* address of first character */
  ,&GUI_Fontsongti16_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti16_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Fontsongti16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsongti16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti16 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsongti16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

