/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songti12.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      12                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Range enabled:        6DF1 - 6DF1                                  *
* Range enabled:        5EA6 - 5EA6                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti12;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0020[ 12] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0021[ 12] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0022[ 12] = { /* code 0022, QUOTATION MARK */
  ________,
  __X_X___,
  _X_X____,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0023[ 12] = { /* code 0023, NUMBER SIGN */
  ________,
  ________,
  __X_X___,
  __X_X___,
  XXXXXX__,
  __X_X___,
  _X_X____,
  XXXXXX__,
  _X_X____,
  _X_X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0024[ 12] = { /* code 0024, DOLLAR SIGN */
  ________,
  __X_____,
  _XXXX___,
  X_X_X___,
  X_X_____,
  _XX_____,
  __XX____,
  __X_X___,
  X_X_X___,
  XXXX____,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0025[ 12] = { /* code 0025, PERCENT SIGN */
  ________,
  ________,
  _X__X___,
  X_X_X___,
  X_XX____,
  _X_X____,
  __X_X___,
  __XX_X__,
  _X_X_X__,
  _X__X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0026[ 12] = { /* code 0026, AMPERSAND */
  ________,
  ________,
  __X_____,
  _X_X____,
  _X_X____,
  _XXXX___,
  X_X_X___,
  X_X_X___,
  X__X____,
  _XX_XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0027[ 12] = { /* code 0027, APOSTROPHE */
  ________,
  _X______,
  _X______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0028[ 12] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  _____X__,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  _____X__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0029[ 12] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  _X______,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_002A[ 12] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  __X_____,
  X_X_X___,
  _XXX____,
  _XXX____,
  X_X_X___,
  __X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_002B[ 12] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_002C[ 12] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_002D[ 12] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_002E[ 12] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_002F[ 12] = { /* code 002F, SOLIDUS */
  ________,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0030[ 12] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0031[ 12] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  __X_____,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0032[ 12] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  ___X____,
  __X_____,
  _X______,
  X_______,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0033[ 12] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  _XXX____,
  X___X___,
  ____X___,
  __XX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0034[ 12] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ___X____,
  __XX____,
  _X_X____,
  _X_X____,
  X__X____,
  _XXXX___,
  ___X____,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0035[ 12] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  XXXXX___,
  X_______,
  X_______,
  XXXX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0036[ 12] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  _XXX____,
  X__X____,
  X_______,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0037[ 12] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  XXXXX___,
  X__X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0038[ 12] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0039[ 12] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ____X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_003A[ 12] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_003B[ 12] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_003C[ 12] = { /* code 003C, LESS-THAN SIGN */
  ________,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_003D[ 12] = { /* code 003D, EQUALS SIGN */
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  ________,
  ________,
  XXXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_003E[ 12] = { /* code 003E, GREATER-THAN SIGN */
  ________,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_003F[ 12] = { /* code 003F, QUESTION MARK */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  ___X____,
  __X_____,
  __X_____,
  ________,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0040[ 12] = { /* code 0040, COMMERCIAL AT */
  ________,
  ________,
  _XXX____,
  X___X___,
  X__XX___,
  X_X_X___,
  X_X_X___,
  X_XXX___,
  X_______,
  _XXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0041[ 12] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  __X_____,
  __X_____,
  __XX____,
  _X_X____,
  _X_X____,
  _XXXX___,
  _X__X___,
  XX__XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0042[ 12] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  XXXX____,
  _X__X___,
  _X__X___,
  _XXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  XXXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0043[ 12] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  _XXXX___,
  X___X___,
  X_______,
  X_______,
  X_______,
  X_______,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0044[ 12] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  XXXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  XXXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0045[ 12] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  XXXXX___,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X______,
  _X__X___,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0046[ 12] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  XXXXX___,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0047[ 12] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,
  ________,
  __XXX___,
  _X__X___,
  X_______,
  X_______,
  X__XXX__,
  X___X___,
  _X__X___,
  __XX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0048[ 12] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,
  ________,
  XX__XX__,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  XX__XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0049[ 12] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_004A[ 12] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  X__X____,
  XXX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_004B[ 12] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  XXX_XX__,
  _X__X___,
  _X_X____,
  _XX_____,
  _X_X____,
  _X_X____,
  _X__X___,
  XXX_XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_004C[ 12] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X___X__,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_004D[ 12] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,
  ________,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_004E[ 12] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,
  ________,
  XX_XXX__,
  _X__X___,
  _XX_X___,
  _XX_X___,
  _X_XX___,
  _X_XX___,
  _X__X___,
  XXX_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_004F[ 12] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0050[ 12] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  XXXX____,
  _X__X___,
  _X__X___,
  _XXX____,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0051[ 12] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,
  ________,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  XXX_X___,
  X__XX___,
  _XXX____,
  ___XX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0052[ 12] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  XXXX____,
  _X__X___,
  _X__X___,
  _XXX____,
  _X_X____,
  _X__X___,
  _X__X___,
  XXX_XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0053[ 12] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  _XXXX___,
  X___X___,
  X_______,
  _XX_____,
  ___X____,
  ____X___,
  X___X___,
  XXXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0054[ 12] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  XXXXX___,
  X_X_X___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0055[ 12] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,
  ________,
  XX__XX__,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  __XX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0056[ 12] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,
  ________,
  XX__XX__,
  _X__X___,
  _X__X___,
  _X_X____,
  _X_X____,
  __XX____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0057[ 12] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,
  ________,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  _XXX____,
  _X_X____,
  _X_X____,
  _X_X____,
  _X_X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0058[ 12] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  XX_XX___,
  _X_X____,
  _X_X____,
  __X_____,
  __X_____,
  _X_X____,
  _X_X____,
  XX_XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0059[ 12] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  XX_XX___,
  _X_X____,
  _X_X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_005A[ 12] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  XXXXX___,
  X__X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X__X___,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_005B[ 12] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,
  __XXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __XXX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_005C[ 12] = { /* code 005C, REVERSE SOLIDUS */
  ________,
  _X______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_005D[ 12] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXX____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_005E[ 12] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,
  __X_____,
  _X_X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_005F[ 12] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0060[ 12] = { /* code 0060, GRAVE ACCENT */
  ________,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0061[ 12] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  __XXX___,
  _X__X___,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0062[ 12] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _XXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0063[ 12] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X__X___,
  _X______,
  _X______,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0064[ 12] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ___XX___,
  ____X___,
  ____X___,
  __XXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0065[ 12] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  _XXXX___,
  _X______,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0066[ 12] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ___XXX__,
  __X_____,
  __X_____,
  _XXXX___,
  __X_____,
  __X_____,
  __X_____,
  _XXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0067[ 12] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X__X___,
  __XX____,
  _X______,
  _XXXX___,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0068[ 12] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _XXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  XXX_XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0069[ 12] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  __X_____,
  ________,
  ________,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_006A[ 12] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ___X____,
  ________,
  ________,
  __XX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_006B[ 12] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X_XXX__,
  _X_X____,
  _XXX____,
  _X__X___,
  XXX_XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_006C[ 12] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_006D[ 12] = { /* code 006D, LATIN SMALL LETTER M */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_006E[ 12] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  XXX_XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_006F[ 12] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  _X__X___,
  _X__X___,
  __XX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0070[ 12] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0071[ 12] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  __XXX___,
  ____X___,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0072[ 12] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX_____,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0073[ 12] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _X______,
  __XX____,
  ____X___,
  _XXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  _XXX____,
  __X_____,
  __X_____,
  __X_____,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0075[ 12] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _X__X___,
  _X__X___,
  _X__X___,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0076[ 12] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XX__,
  _X__X___,
  _X_X____,
  __XX____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0077[ 12] = { /* code 0077, LATIN SMALL LETTER W */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_X___,
  X_X_X___,
  _XXX____,
  _X_X____,
  _X_X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0078[ 12] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _X_X____,
  __X_____,
  _X_X____,
  XX_XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_0079[ 12] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XX__,
  _X__X___,
  _X_X____,
  __XX____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_007A[ 12] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  ___X____,
  __X_____,
  __X_____,
  _XXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_007B[ 12] = { /* code 007B, LEFT CURLY BRACKET */
  ________,
  ___XX___,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___XX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_007C[ 12] = { /* code 007C, VERTICAL LINE */
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_007D[ 12] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_007E[ 12] = { /* code 007E, TILDE */
  _X______,
  X_X__X__,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_007F[ 12] = { /* code 007F, <control> */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_00B0[ 24] = { /* code 00B0, DEGREE SIGN */
  ________,________,
  __XX____,________,
  _X__X___,________,
  _X__X___,________,
  __XX____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <Letterlike Symbols> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_2103[ 24] = { /* code 2103, DEGREE CELSIUS */
  _X______,________,
  X_X__XXX,_X______,
  _X__X___,XX______,
  ___X____,_X______,
  ___X____,________,
  ___X____,________,
  ___X____,________,
  ___X____,__X_____,
  ____X___,_X______,
  _____XXX,X_______,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_4F4D[ 24] = { /* code 4F4D */
  __X___X_,________,
  __X____X,________,
  _X______,________,
  _X_XXXXX,XXX_____,
  XX______,________,
  _X__X___,_X______,
  _X__X___,_X______,
  _X___X__,_X______,
  _X___X__,X_______,
  _X___X__,X_______,
  _X_____X,________,
  _X_XXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_536B[ 24] = { /* code 536B */
  ________,________,
  _XXXXXXX,XX______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X_XX,X_______,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_5B9A[ 24] = { /* code 5B9A */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  ________,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __X__X__,________,
  __X__XXX,XX______,
  __X__X__,________,
  _X_X_X__,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_5EA6[ 24] = { /* code 5EA6 */
  ______X_,________,
  _XXXXXXX,XXX_____,
  _X__X___,X_______,
  _XXXXXXX,XXX_____,
  _X__X___,X_______,
  _X__XXXX,X_______,
  _X______,________,
  _X_XXXXX,XX______,
  _X__X___,_X______,
  _X___X__,X_______,
  _X____XX,________,
  X__XXX__,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_6447[ 24] = { /* code 6447 */
  __X_____,XXX_____,
  __X_XXXX,________,
  __X___X_,__X_____,
  XXXXX__X,_X______,
  __X__X__,________,
  __X__XXX,XX______,
  __XXX__X,________,
  XXX____X,________,
  __X_XXXX,XXX_____,
  __X____X,________,
  __X_X__X,__X_____,
  _XX_XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_661F[ 24] = { /* code 661F */
  _XXXXXXX,XX______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  _X___X__,________,
  _XXXXXXX,XX______,
  X____X__,________,
  __XXXXXX,X_______,
  _____X__,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_6A2A[ 24] = { /* code 6A2A */
  __X__X__,_X______,
  __X_XXXX,XXX_____,
  XXXX_X__,_X______,
  __X_XXXX,XXX_____,
  __X____X,________,
  _XXXXXXX,XXX_____,
  _XX_X__X,__X_____,
  X_X_XXXX,XXX_____,
  __X_X__X,__X_____,
  __X_XXXX,XXX_____,
  __X__X__,_X______,
  __X_X___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_6C34[ 24] = { /* code 6C34 */
  _____X__,________,
  _____X__,________,
  _____X__,__X_____,
  _XXX_XX_,_X______,
  ___X_XX_,X_______,
  ___X_X_X,________,
  ___X_X_X,________,
  __X__X__,X_______,
  __X__X__,X_______,
  _X___X__,_X______,
  X____X__,__X_____,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_6DF1[ 24] = { /* code 6DF1 */
  ________,________,
  X_XXXXXX,XXX_____,
  _XX__X_X,__X_____,
  ____X___,X_______,
  ___X__X_,_X______,
  X_____X_,________,
  _X_XXXXX,XXX_____,
  ______X_,________,
  _____XXX,________,
  _X__X_X_,X_______,
  X_XX__X_,_XX_____,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_6E29[ 24] = { /* code 6E29 */
  ____XXXX,X_______,
  X___X___,X_______,
  _X__XXXX,X_______,
  ____X___,X_______,
  ____XXXX,X_______,
  X_______,________,
  _X_XXXXX,XX______,
  ___X_X_X,_X______,
  __XX_X_X,_X______,
  _X_X_X_X,_X______,
  X__X_X_X,_X______,
  __XXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_7EB5[ 24] = { /* code 7EB5 */
  __X__X__,X_______,
  __X__X__,X_______,
  _X___X__,X_______,
  X__X_X__,X_______,
  XXX__X__,X_______,
  __X__X__,X_______,
  _X___X__,X_______,
  XXX__X__,X_______,
  ____X_XX,_X______,
  __X_X__X,_X______,
  XX_X__X_,_X______,
  __X__X__,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_7F6E[ 24] = { /* code 7F6E */
  _XXXXXXX,XX______,
  _X__X_X_,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __XXXXXX,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X__X__,X_______,
  __X__X__,X_______,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_8239[ 24] = { /* code 8239 */
  ___X____,________,
  __X___XX,XX______,
  _XXXX_X_,_X______,
  _X__X_X_,_X______,
  _XX_XX__,__X_____,
  _X_XX___,________,
  XXXXX_XX,XX______,
  _X__X_X_,_X______,
  _XX_X_X_,_X______,
  _X_XX_X_,_X______,
  _X__X_XX,XX______,
  X__XX_X_,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_8258[ 24] = { /* code 8258 */
  __X____X,________,
  _XXX__XX,_XX_____,
  _X_X_X_X,__X_____,
  _XXX_XXX,_XX_____,
  _X_X_X_X,__X_____,
  XXXX_XXX,XXX_____,
  _X_X___X,________,
  _XXX_XXX,XXX_____,
  _X_X__X_,__X_____,
  _X_X___X,_X______,
  _X_X___X,X_______,
  X_XX_XX_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti12_901F[ 24] = { /* code 901F */
  X_____X_,________,
  _X_XXXXX,XXX_____,
  ______X_,________,
  ___XXXXX,XX______,
  XX_X__X_,_X______,
  _X_X__X_,_X______,
  _X_XXXXX,XX______,
  _X___XXX,________,
  _X__X_X_,X_______,
  _X_X__X_,_X______,
  _X____X_,________,
  X_XXXXXX,XXX_____};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsongti12_CharInfo[113] = {
   {   6,   6,  1, acGUI_Fontsongti12_0020 } /* code 0020 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0021 } /* code 0021 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0022 } /* code 0022 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0023 } /* code 0023 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0024 } /* code 0024 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0025 } /* code 0025 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0026 } /* code 0026 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0027 } /* code 0027 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0028 } /* code 0028 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0029 } /* code 0029 */
  ,{   6,   6,  1, acGUI_Fontsongti12_002A } /* code 002A */
  ,{   6,   6,  1, acGUI_Fontsongti12_002B } /* code 002B */
  ,{   6,   6,  1, acGUI_Fontsongti12_002C } /* code 002C */
  ,{   6,   6,  1, acGUI_Fontsongti12_002D } /* code 002D */
  ,{   6,   6,  1, acGUI_Fontsongti12_002E } /* code 002E */
  ,{   6,   6,  1, acGUI_Fontsongti12_002F } /* code 002F */
  ,{   6,   6,  1, acGUI_Fontsongti12_0030 } /* code 0030 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0031 } /* code 0031 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0032 } /* code 0032 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0033 } /* code 0033 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0034 } /* code 0034 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0035 } /* code 0035 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0036 } /* code 0036 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0037 } /* code 0037 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0038 } /* code 0038 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0039 } /* code 0039 */
  ,{   6,   6,  1, acGUI_Fontsongti12_003A } /* code 003A */
  ,{   6,   6,  1, acGUI_Fontsongti12_003B } /* code 003B */
  ,{   6,   6,  1, acGUI_Fontsongti12_003C } /* code 003C */
  ,{   6,   6,  1, acGUI_Fontsongti12_003D } /* code 003D */
  ,{   6,   6,  1, acGUI_Fontsongti12_003E } /* code 003E */
  ,{   6,   6,  1, acGUI_Fontsongti12_003F } /* code 003F */
  ,{   6,   6,  1, acGUI_Fontsongti12_0040 } /* code 0040 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0041 } /* code 0041 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0042 } /* code 0042 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0043 } /* code 0043 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0044 } /* code 0044 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0045 } /* code 0045 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0046 } /* code 0046 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0047 } /* code 0047 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0048 } /* code 0048 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0049 } /* code 0049 */
  ,{   6,   6,  1, acGUI_Fontsongti12_004A } /* code 004A */
  ,{   6,   6,  1, acGUI_Fontsongti12_004B } /* code 004B */
  ,{   6,   6,  1, acGUI_Fontsongti12_004C } /* code 004C */
  ,{   6,   6,  1, acGUI_Fontsongti12_004D } /* code 004D */
  ,{   6,   6,  1, acGUI_Fontsongti12_004E } /* code 004E */
  ,{   6,   6,  1, acGUI_Fontsongti12_004F } /* code 004F */
  ,{   6,   6,  1, acGUI_Fontsongti12_0050 } /* code 0050 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0051 } /* code 0051 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0052 } /* code 0052 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0053 } /* code 0053 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0054 } /* code 0054 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0055 } /* code 0055 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0056 } /* code 0056 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0057 } /* code 0057 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0058 } /* code 0058 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0059 } /* code 0059 */
  ,{   6,   6,  1, acGUI_Fontsongti12_005A } /* code 005A */
  ,{   6,   6,  1, acGUI_Fontsongti12_005B } /* code 005B */
  ,{   6,   6,  1, acGUI_Fontsongti12_005C } /* code 005C */
  ,{   6,   6,  1, acGUI_Fontsongti12_005D } /* code 005D */
  ,{   6,   6,  1, acGUI_Fontsongti12_005E } /* code 005E */
  ,{   6,   6,  1, acGUI_Fontsongti12_005F } /* code 005F */
  ,{   6,   6,  1, acGUI_Fontsongti12_0060 } /* code 0060 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0061 } /* code 0061 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0062 } /* code 0062 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0063 } /* code 0063 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0064 } /* code 0064 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0065 } /* code 0065 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0066 } /* code 0066 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0067 } /* code 0067 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0068 } /* code 0068 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0069 } /* code 0069 */
  ,{   6,   6,  1, acGUI_Fontsongti12_006A } /* code 006A */
  ,{   6,   6,  1, acGUI_Fontsongti12_006B } /* code 006B */
  ,{   6,   6,  1, acGUI_Fontsongti12_006C } /* code 006C */
  ,{   6,   6,  1, acGUI_Fontsongti12_006D } /* code 006D */
  ,{   6,   6,  1, acGUI_Fontsongti12_006E } /* code 006E */
  ,{   6,   6,  1, acGUI_Fontsongti12_006F } /* code 006F */
  ,{   6,   6,  1, acGUI_Fontsongti12_0070 } /* code 0070 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0071 } /* code 0071 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0072 } /* code 0072 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0073 } /* code 0073 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0074 } /* code 0074 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0075 } /* code 0075 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0076 } /* code 0076 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0077 } /* code 0077 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0078 } /* code 0078 */
  ,{   6,   6,  1, acGUI_Fontsongti12_0079 } /* code 0079 */
  ,{   6,   6,  1, acGUI_Fontsongti12_007A } /* code 007A */
  ,{   6,   6,  1, acGUI_Fontsongti12_007B } /* code 007B */
  ,{   6,   6,  1, acGUI_Fontsongti12_007C } /* code 007C */
  ,{   6,   6,  1, acGUI_Fontsongti12_007D } /* code 007D */
  ,{   6,   6,  1, acGUI_Fontsongti12_007E } /* code 007E */
  ,{   6,   6,  1, acGUI_Fontsongti12_007F } /* code 007F */
  ,{  12,  12,  2, acGUI_Fontsongti12_00B0 } /* code 00B0 */
  ,{  12,  12,  2, acGUI_Fontsongti12_2103 } /* code 2103 */
  ,{  12,  12,  2, acGUI_Fontsongti12_4F4D } /* code 4F4D */
  ,{  12,  12,  2, acGUI_Fontsongti12_536B } /* code 536B */
  ,{  12,  12,  2, acGUI_Fontsongti12_5B9A } /* code 5B9A */
  ,{  12,  12,  2, acGUI_Fontsongti12_5EA6 } /* code 5EA6 */
  ,{  12,  12,  2, acGUI_Fontsongti12_6447 } /* code 6447 */
  ,{  12,  12,  2, acGUI_Fontsongti12_661F } /* code 661F */
  ,{  12,  12,  2, acGUI_Fontsongti12_6A2A } /* code 6A2A */
  ,{  12,  12,  2, acGUI_Fontsongti12_6C34 } /* code 6C34 */
  ,{  12,  12,  2, acGUI_Fontsongti12_6DF1 } /* code 6DF1 */
  ,{  12,  12,  2, acGUI_Fontsongti12_6E29 } /* code 6E29 */
  ,{  12,  12,  2, acGUI_Fontsongti12_7EB5 } /* code 7EB5 */
  ,{  12,  12,  2, acGUI_Fontsongti12_7F6E } /* code 7F6E */
  ,{  12,  12,  2, acGUI_Fontsongti12_8239 } /* code 8239 */
  ,{  12,  12,  2, acGUI_Fontsongti12_8258 } /* code 8258 */
  ,{  12,  12,  2, acGUI_Fontsongti12_901F } /* code 901F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop18 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_Fontsongti12_CharInfo[112] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop17 = {
   0x8258 /* first character */
  ,0x8258 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[111] /* address of first character */
  ,&GUI_Fontsongti12_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop16 = {
   0x8239 /* first character */
  ,0x8239 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[110] /* address of first character */
  ,&GUI_Fontsongti12_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop15 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Fontsongti12_CharInfo[109] /* address of first character */
  ,&GUI_Fontsongti12_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop14 = {
   0x7EB5 /* first character */
  ,0x7EB5 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[108] /* address of first character */
  ,&GUI_Fontsongti12_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop13 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[107] /* address of first character */
  ,&GUI_Fontsongti12_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop12 = {
   0x6DF1 /* first character */
  ,0x6DF1 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[106] /* address of first character */
  ,&GUI_Fontsongti12_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop11 = {
   0x6C34 /* first character */
  ,0x6C34 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[105] /* address of first character */
  ,&GUI_Fontsongti12_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop10 = {
   0x6A2A /* first character */
  ,0x6A2A /* last character  */
  ,&GUI_Fontsongti12_CharInfo[104] /* address of first character */
  ,&GUI_Fontsongti12_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop9 = {
   0x661F /* first character */
  ,0x661F /* last character  */
  ,&GUI_Fontsongti12_CharInfo[103] /* address of first character */
  ,&GUI_Fontsongti12_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop8 = {
   0x6447 /* first character */
  ,0x6447 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[102] /* address of first character */
  ,&GUI_Fontsongti12_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop7 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[101] /* address of first character */
  ,&GUI_Fontsongti12_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop6 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_Fontsongti12_CharInfo[100] /* address of first character */
  ,&GUI_Fontsongti12_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop5 = {
   0x536B /* first character */
  ,0x536B /* last character  */
  ,&GUI_Fontsongti12_CharInfo[ 99] /* address of first character */
  ,&GUI_Fontsongti12_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop4 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontsongti12_CharInfo[ 98] /* address of first character */
  ,&GUI_Fontsongti12_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop3 = {
   0x2103 /* first character */
  ,0x2103 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[ 97] /* address of first character */
  ,&GUI_Fontsongti12_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop2 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_Fontsongti12_CharInfo[ 96] /* address of first character */
  ,&GUI_Fontsongti12_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti12_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Fontsongti12_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsongti12_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti12 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,12 /* height of font  */
  ,12 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsongti12_Prop1}
  ,10 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

